### ISSUE TITLE
[BUG] Running scripts aren't cleared upon script termination

### ISSUE THREAD

**Issue by ParadoxPython** [Natashi/Touhou-Danmakufu-ph3sx-2#20]
I got this error after restarting the same script multiple times (the path it's pointing to is a library that gets StartScript'd from the System): https://prnt.sc/x0ou57

Checking the log window's script tab, running scripts are never cleared when restarting or existing out of a script, and the script IDs keep counting up. The error occurs when trying to restart after script ID 119 is reached (another 9 scripts would be added, so the max is somewhere around there; the path it's pointing to is always the 5th script in the list). Restarting the program resets script IDs to begin counting up from 1 again.

**Comment by Pikachuun** [comment]
Before I forget to mention this since it came to me while reading the issue, the ID incrementation behavior is identical to vanilla ph3; it doesn't have anything to do with the crash itself.
The running scripts not being cleared is... also a vanilla ph3 issue. I think the window just doesn't update if there aren't any running scripts (there's no reason to if there's nothing there, right?), probably just assuming the window would be blank or something.

The issue was still very real though; I personally found it by checking the Texture tab and seeing none of the objects being destroyed, even though the texture thing turned out to not be the actual bug
Anyways that pull request should fix it (aka it didn't happen to me when I tested it post-changes), just have to wait on a merge
